# Generated by Django 3.0.6 on 2020-06-16 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='AlMa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calif', models.PositiveIntegerField(verbose_name='calificacion')),
                ('k_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promedio.Alumno')),
                ('k_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promedio.Materia')),
            ],
        ),
    ]
